from datetime import datetime

replace_strings = [
    "(Full Content) Gippy Grewal | Gurpreet Ghuggi | Geeta Basra | New Punjabi Full Content | SagaMusic",
    "- Director’s Cut (plus Kinofassung)",
    "(Originalfassung) (Mit Untertiteln)",
    "(Originalfassung) (Mit Untertitel)",
    "(Documentaries) [DOCUMENTARIES]",
    "(Unrated Extended Cut Version)",
    "(Version longue non censurÃ©e)",
    "(Version longue non censurÃ©e)",
    "(20th Anniversary HD Edition)",
    "(Con subtÃ­tulos en espaÃ±ol)",
    "(Original Version)(Subtitled)",
    " (Original Japanese Version)",
    "- CapÃ­tulos 1 y 2 (V.O.S.E)",
    "(Version FranÃ§aise Incluse)",
    "(Internationale Kinofassung)",
    "[Internationale Kinofassung]",
    " (Extended Cut) (Subtitled)",
    "(Original Japanese Version)",
    "(50th Anniversary Edition)",
    "(Extended Director's Cut)",
    " (Incluye material extra)",
    "(Sottotitoli in italiano)",
    "(Version Longue InÃ©dite)",
    " (Doblada y Subtitulada)",
    " [Doblada y Subtitulada]",
    "- Extended Edition Content",
    "(Extended Dance Edition)",
    "(Unrated Director's Cut)",
    ": The Complete Series 19",
    ": The Complete Series 18",
    ": The Complete Series 16",
    ": The Complete Series 15",
    ": The Complete Series 14",
    ": The Complete Series 12",
    "- CapÃ­tulos 1 y 2 (ESP)",
    "(English Dubbed Version)",
    "(ungeschnittene Fassung)",
    "Extended Director's Cut",
    "(International Version)",
    "(Inclui Material Extra)",
    "[International Version]",
    "[Inclui Material Extra]",
    "(Unrated Extended Cut)",
    "(Dublado y Legendado)",
    "[Dublado y Legendado]",
    "(Collector's Edition)",
    "(In Color & Restored)",
    "(Plus Bonus Features)",
    "(con Material Extra)",
    "(plus Bonus Feature)",
    "- 2 Content Collection",
    "- Director's Fan Cut",
    "(Digital Remastered)",
    "(Remastered Edition)",
    "(Versione Integrale)",
    "(Version RestaurÃ©e)",
    "/ Digital Remastered",
    "(International Dubs)",
    "(Olympus Has Fallen)",
    "[International Dubs]",
    "[Olympus Has Fallen]",
    "(English Subtitles)",
    "(French connection)",
    "(Extended Version)",
    "(Extended Edition)",
    ", Saison 4, Vol. 1",
    "(Med undertekster)",
    "(Original Version)",
    "(Restored Version)",
    "(Original Version)",
    "(Ultimate Edition)",
    ", Saison 3, Vol.3",
    "(Mit Untertiteln)",
    "(Originalfassung)",
    "(Special Edition)",
    "(Unrated Edition)",
    "(Director's Cut)",
    "[Director's Cut]",
    ": Director's Cut",
    "- Director's Cut",
    "(VOST) [Unrated]",
    "(version longue)",
    "(Synchronisiert)",
    "(Double Trouble)",
    "[Double Trouble]",
    "- Uncut Edition",
    "(Uncut Edition)",
    "(UNCUT EDITION)",
    "(Uncut Version)",
    ", Volumes 1 - 3",
    "(International)",
    "(Intersections)",
    "[International]",
    "[Intersections]",
    "(Spanish Audio)",
    "(Extended Cut)",
    "[Extended Cut]",
    "(Extended Cut)",
    " Director's Cut",
    " (Subtitulada)",
    " [Subtitulada]",
    "(VF) [Unrated]",
    "[Anglais VOST]",
    "- Extended Cut",
    " (En Espanol)",
    "(Unrated Cut)",
    " (Since 1921)",
    ": Seasons 1-5",
    "- prima parte",
    "(Re-mastered)",
    "(Tekstitetty)",
    "(Untertitelt)",
    "(Subtitulada)",
    "(Subtitulado)",
    "[Subtitulado]",
    "Prima Visione",
    "(SUBTITULADA)",
    "(Theatrical)",
    "(theatrical)",
    "(AnimaciÃ³n)",
    "La PelÃ­cula",
    "(Dansk tale)",
    "(in Italian)",
    "(Norsk tale)",
    "(Sing-Along)",
    "(Unzensiert)",
    "[Remastered]",
    "[En Espanol]",
    "(Read Along)",
    "(En Español)",
    "(Legendado)",
    "[Legendado]",
    "(Subtitled)",
    "(animacion)",
    "(Suomi dub)",
    "(suomi dub)",
    "Rated 18 |",
    "[Subtitled]",
    "- Saison 1",
    "(Animated)",
    "(Censored)",
    "(Doppiato)",
    "(In Color)",
    "(Extended)",
    "- Extended",
    "(Doblada)",
    "(DOBLADA)",
    "[Doblada]",
    "(Dublado)",
    "[Dublado]",
    "(Unrated)",
    "[Unrated]",
    " (V.O.S.)",
    "(feature)",
    ": Le film",
    "(Dublado)",
    "(Doblado)",
    "[Doblado]",
    "(Dobalda)",
    "- Filmen",
    "(Dubbed)",
    "Der Film",
    "(Subbed)",
    "(Remake)",
    "(V.O.S)",
    "- Uncut",
    "(Uncut)",
    "(UNCUT)",
    " (Live)",
    "Le film",
    " Bonus",
    "(Rated)",
    "(VOST)",
    "(DVD)",
    "(VOS)",
    "(Sub)",
    "(SUB)",
    "(Dob)"
    "(ESP)",
    "(OmU)",
    " 1&2",
    " 1-2",
    "(SD)",
    "[VF]",
    "(HD)",
    "[HD]",
    "(VF)",
    "(VE)",
    "(f)",
    "()",
    "HD",
    "SD",
]


def _replace(content_title):
    this_year = datetime.now().year
    this_year = 1  # Le sumo uno porque range arranca a contar de 0.

    for i in range(1870, this_year):
        content_title = content_title.replace('({})'.format(i), '')
        content_title = content_title.replace('[{}]'.format(i), '')

    for i in sorted(replace_strings, reverse=True, key=len):
        content_title = content_title.replace(i, '')

    return content_title.strip()
